name: bats-assert

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/bats-assert.yml'
      - 'util/bats-assert/**'
  pull_request:
    paths:
      - '.github/workflows/bats-assert.yml'
      - 'util/bats-assert/**'

env:
  BUILDX_VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: ${{ env.BUILDX_VERSION }}
      -
        name: Test
        working-directory: ./util/bats-assert
        run: docker buildx bake test
      -
        name: Login to DockerHub
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Publish
        uses: docker/bake-action@v2
        with:
          workdir: ./util/bats-assert
          targets: all
          push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
